name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Set GOPATH
        # We take the dirname of $GITHUB_WORKSPACE because, for some reason,
        # by default it's `/home/runner/work/paas-rds-broker/paas-rds/broker`
        # but when we checkout the source it drops the second mention of the
        # repo name
        run: |
          echo GOPATH=$(dirname $GITHUB_WORKSPACE) >> $GITHUB_ENV
        id: gopath


      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          # Path must be relative to /home/runner
          # https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Sdk/Util/IOUtil.cs#L300
          #
          # We need to checkout the code in to a GOPATH-like place.
          # We set the GOPATH to the original $GITHUB_WORKSPACE earlier.
          path: src/github.com/alphagov/paas-rds-broker
        id: checkout

      - name: Create GOBIN directory
        run: |
          mkdir $GOPATH/bin
          echo GOBIN=$GOPATH/bin >> $GITHUB_ENV
          echo $GOPATH/bin >> $GITHUB_PATH
        id: gobin

      - name: Install Ginkgo CLI
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo

      - name: Run tests
        run: |
          make test_unit

      - name: Run postgres 10 tests
        run: |
          make start_postgres_10 run_postgres_sql_tests stop_postgres_10

      - name: Run postgres 11 tests
        run: |
          make start_postgres_11 run_postgres_sql_tests stop_postgres_11

      - name: Run postgres 12 tests
        run: |
          make start_postgres_12 run_postgres_sql_tests stop_postgres_12

      - name: Run mysql 8.0
        run: |
          make start_mysql_80 run_mysql_sql_tests stop_mysql_80

      - name: Run mysql 5.7
        run: |
          make start_mysql_57 run_mysql_sql_tests stop_mysql_57
